name: Deploy AWS Lambda

# Main event listener when there is any GitHub push
on:
  push:
    branches:
      - main
    paths:
      - 'lambda/**'

jobs:
  # Name of the overall job
  deploy-lambda:
    # Sets up the runner
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/

      # Configure AWS credentials
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: eu-north-1

      # Zip the Lambda directory and update the Lambda function
      - name: Deploy Lambda Function
        run: |
          cd lambda
          zip -r lambda.zip .
          aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip
